/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AdminAdminPost - 添加管理员
func AdminAdminPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminLoginPost - 登录-管理员
func AdminLoginPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUserGet - 查询用户
func AdminUserGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUserPost - 添加用户
func AdminUserPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUserUserIDGet - 根据ID查用户
func AdminUserUserIDGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUserUserIDPut - 修改用户
func AdminUserUserIDPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AnnouncementDelete - 删除公告
func AnnouncementDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AnnouncementPost - 添加公告
func AnnouncementPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DetailGet - 获取-商品详情
func DetailGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HomeCategoryGet - 获取-全部分类
func HomeCategoryGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MemberAddressGet - 获取-收货地址
func MemberAddressGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MemberAddressIdDelete - 删除-收货地址
func MemberAddressIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MemberAddressIdPut - 修改-收货地址
func MemberAddressIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MemberAddressPost - 添加-收货地址
func MemberAddressPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// OrdersPurchasedGet - 获取-我买到的
func OrdersPurchasedGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// OrdersSelledGet - 获取-我卖出的
func OrdersSelledGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostGoodsPost - 添加-发布闲置
func PostGoodsPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ProductSelectGet - 筛选商品
func ProductSelectGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ProductsGet - 获取-商品列表
func ProductsGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
