/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject2 struct {

	// 地址唯一ID
	Id int32 `json:"id"`

	// 拥有地址的用户ID
	UserID int32 `json:"userID"`

	// 收件人姓名
	Name string `json:"name"`

	// 电话号码
	Tel string `json:"tel"`

	// 详细地址
	Address string `json:"address"`

	// 是否为默认，0是，1不是
	IsDefault int32 `json:"isDefault"`
}
