/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DingDan struct {

	// 订单ID
	TradeID int32 `json:"tradeID"`

	// 卖家ID
	SellerID int32 `json:"sellerID"`

	// 卖家昵称
	SellerName string `json:"sellerName"`

	// 商品ID
	GoodsID int32 `json:"goodsID"`

	// 商品名称
	GoodsName string `json:"goodsName"`

	// 价格
	Price float32 `json:"price"`

	// 交易方式，邮寄、自提、无需快递
	DeliveryMethod string `json:"deliveryMethod"`

	// 运费
	ShippingCost float32 `json:"shippingCost"`

	SenderAddress SendAddress `json:"SenderAddress"`

	ShippingAddress ShipAddress `json:"shippingAddress,omitempty"`

	// 下单时间
	OrderTime string `json:"orderTime,omitempty"`

	// 支付时间
	PayTime string `json:"payTime,omitempty"`

	// 发货时间
	ShippingTime string `json:"shippingTime,omitempty"`

	// 成交时间
	TurnoverTime string `json:"turnoverTime,omitempty"`

	// 订单状态
	Status string `json:"status"`
}
