/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20011 struct {

	// 业务状态码，1为成功
	Code int32 `json:"code"`

	// 响应消息
	Msg string `json:"msg"`

	// 响应结果
	Data []DingDan `json:"data"`
}
