/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2006 struct {

	Code int32 `json:"code"`

	Data InlineResponse2006Data `json:"data"`

	Msg string `json:"msg"`
}
