/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject struct {

	AdminID int32 `json:"adminID"`

	Password string `json:"password"`

	Tel string `json:"tel,omitempty"`

	Mail string `json:"mail,omitempty"`

	Gender int32 `json:"gender,omitempty"`

	Age int32 `json:"age,omitempty"`
}
