/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// 2 - 收货地址
type ShipAddress struct {

	// 省
	Province string `json:"province"`

	// 市
	City string `json:"city"`

	// 区
	Area string `json:"area"`

	// 详细地址
	DetailArea string `json:"detailArea"`
}
