/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject3 struct {

	// 发布者ID
	UserID string `json:"userID"`

	// 商品名
	Name string `json:"name"`

	// 商品描述
	Describe string `json:"describe"`

	// 售价
	Price string `json:"price"`

	// 商品类别
	Category int32 `json:"category"`

	// 图片url
	Image string `json:"image"`

	// 地址
	Address string `json:"address"`

	// 配送方式，1邮寄，2自提， 3无需快递
	Delivery int32 `json:"delivery"`

	// 运费，delivery为2或3时，此项为0
	Fare string `json:"fare"`
}
