/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CategoryShangPinFenLei struct {

	CategoryID int32 `json:"categoryID"`

	CategoryName string `json:"categoryName"`

	Description string `json:"description,omitempty"`
}
