/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2005 struct {

	Code int32 `json:"code"`

	Msg string `json:"msg"`

	Data map[string]interface{} `json:"data"`

	// 收货地址id
	Id string `json:"id"`
}
