/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2008Data struct {

	// 商品ID，ID 编号
	Id int32 `json:"id"`

	// 商品名
	Name string `json:"name"`

	// 价格
	Price int32 `json:"price"`

	// 商品首图
	Picture string `json:"picture"`

	// 分类ID，分组
	CategoryID string `json:"categoryID"`
}
