/*
 * 二手交易平台
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"AdminAdminPost",
		http.MethodPost,
		"/admin/admin",
		AdminAdminPost,
	},

	{
		"AdminLoginPost",
		http.MethodPost,
		"/admin/login",
		AdminLoginPost,
	},

	{
		"AdminUserGet",
		http.MethodGet,
		"/admin/user",
		AdminUserGet,
	},

	{
		"AdminUserPost",
		http.MethodPost,
		"/admin/user",
		AdminUserPost,
	},

	{
		"AdminUserUserIDGet",
		http.MethodGet,
		"/admin/user/:userID",
		AdminUserUserIDGet,
	},

	{
		"AdminUserUserIDPut",
		http.MethodPut,
		"/admin/user/:userID",
		AdminUserUserIDPut,
	},

	{
		"AnnouncementDelete",
		http.MethodDelete,
		"/announcement",
		AnnouncementDelete,
	},

	{
		"AnnouncementPost",
		http.MethodPost,
		"/announcement",
		AnnouncementPost,
	},

	{
		"DetailGet",
		http.MethodGet,
		"/detail",
		DetailGet,
	},

	{
		"HomeCategoryGet",
		http.MethodGet,
		"/home/category",
		HomeCategoryGet,
	},

	{
		"MemberAddressGet",
		http.MethodGet,
		"/member/address",
		MemberAddressGet,
	},

	{
		"MemberAddressIdDelete",
		http.MethodDelete,
		"/member/address/:id",
		MemberAddressIdDelete,
	},

	{
		"MemberAddressIdPut",
		http.MethodPut,
		"/member/address/:id",
		MemberAddressIdPut,
	},

	{
		"MemberAddressPost",
		http.MethodPost,
		"/member/address",
		MemberAddressPost,
	},

	{
		"OrdersPurchasedGet",
		http.MethodGet,
		"/orders/purchased",
		OrdersPurchasedGet,
	},

	{
		"OrdersSelledGet",
		http.MethodGet,
		"/orders/selled",
		OrdersSelledGet,
	},

	{
		"PostGoodsPost",
		http.MethodPost,
		"/postGoods",
		PostGoodsPost,
	},

	{
		"ProductSelectGet",
		http.MethodGet,
		"/product/select",
		ProductSelectGet,
	},

	{
		"ProductsGet",
		http.MethodGet,
		"/products",
		ProductsGet,
	},
}
